name: Build

on:
  push:
    branches:
      - main
      # Add more branches as needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up C++ environment
      uses: actions/setup-cxx@v2
      with:
        cxx-version: '17' # Specify the desired C++ version

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
